version: '3.5'

services:
  api:
    build: .
    environment:
     - EXTERNAL_HOST=${EXTERNAL_HOST:-http://localhost}
     - WEB_CONCURRENCY=4
     - HOST=0.0.0.0
    ports:
     - "80:80"
    networks:
     - pi2

networks:
  pi2:
    external: true
