version: '3.5'

services:
  net_api:
    build: .
    environment:
     - EXTERNAL_HOST=${EXTERNAL_HOST:-http://localhost}
     - BACKEND_URL=${BACKEND_URL:-http://server:4000/}
     - HOST=0.0.0.0
    ports:
     - "80:80"
    volumes:
      - ./app:/app
      - /home/thiago/Desktop/UnB/pi2/main-server/public/:/app/public

volumes:
  static-files:
    external:
      name: main-server_static-files
